import ollama
import datetime 

def summarize_article(title, content_snippet):
    """
    Uses local Gemma 2 to create a 1-sentence executive summary.
    """
    prompt = f"""
    You are an expert news curator. Summarize the following news article 
    in exactly one sentence for a busy executive.
    
    Title: {title}
    Content: {content_snippet}
    
    Summary:
    """
    
    try:
        response = ollama.generate(model='gemma2', prompt=prompt)
        return response['response'].strip()
    except Exception as e:
        return f"Error summarizing: {str(e)}"
    
def create_markdown_report(summaries):
    """
    Takes a list of summaries and saves them to a structured Markdown file.
    """
    date_str = datetime.date.today().strftime("%Y-%m-%d")
    filename = f"reports/Briefing_{date_str}.md"
    
    content = f"# 🗞️ Hermes Daily Briefing - {date_str}\n\n"
    content += "Generated by Gemma 2 via Hermes Bot\n\n---\n\n"
    
    for item in summaries:
        content += f"### {item['title']}\n"
        content += f"> **Summary:** {item['summary']}\n\n"
        content += f"[Read Original Article]({item['link']})\n\n---\n"
    
    # Ensure the reports folder exists
    import os
    os.makedirs('reports', exist_ok=True)
    
    with open(filename, "w") as f:
        f.write(content)
    
    return filename

# Quick Test logic
if __name__ == "__main__":
    test_title = "Google's Gemma 2 dominates open-source benchmarks"
    test_content = "Gemma 2 9B has shown incredible performance, surpassing models twice its size..."
    print(f"Summary: {summarize_article(test_title, test_content)}")